---
- name: Add transport.ssl.keystore.secure_password to keystore
  command: "{{ elasticsearch_tools_path }}/bin/elasticsearch-keystore add xpack.security.transport.ssl.keystore.secure_password -f"
  args:
    stdin: "{{ cert_pass }}"
  
- name: Add transport.ssl.truststore.secure_password to keystore
  command: "{{ elasticsearch_tools_path }}/bin/elasticsearch-keystore add xpack.security.transport.ssl.truststore.secure_password -f"
  args:
    stdin: "{{ cert_pass }}"
  
- name: Add http.ssl.keystore.secure_password to keystore
  command: "{{ elasticsearch_tools_path }}/bin/elasticsearch-keystore add xpack.security.http.ssl.keystore.secure_password -f"
  args:
    stdin: "{{ cert_pass }}"
  