---
- name: Reset password for elastic user
  ansible.builtin.shell: |
    (echo "y"; echo "{{ elastic_pass }}"; echo "{{ elastic_pass }}") | /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -i > /dev/null 2>&1
