---
- name: Import keystore from src to dest using keytool
  ansible.builtin.shell: |
    keytool -importkeystore \
      -destkeystore /etc/elasticsearch/certs/http.p12 \
      -srckeystore /usr/share/elasticsearch/elastic-stack-ca.p12 \
      -srcstoretype PKCS12 \
      -deststorepass "{{ cert_pass }}" \
      -srcstorepass "{{ cert_pass }}" \
      -noprompt > /dev/null 2>&1
